version: '{build}'

install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install

build: off

clone_folder: c:\mittsu

environment:
  MITTSU_LIBGLFW_FILE: c:\mittsu\glfw3\lib-vc2015\glfw3.dll

install:
  ps: install_glfw.ps

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake test
